import { useState } from 'react'
import { verifyAuditLog, type SignedAuditLog } from '../lib/audit'
import { sampleAuditLog } from '../data/samples'

export function AuditVerifier() {
  const [raw, setRaw] = useState('')
  const [result, setResult] = useState<ReturnType<typeof verifyAuditLog> | null>(
    null,
  )
  const [error, setError] = useState<string | null>(null)

  const handleVerify = () => {
    setError(null)
    setResult(null)
    try {
      const parsed = JSON.parse(raw) as SignedAuditLog
      const outcome = verifyAuditLog(parsed)
      setResult(outcome)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Invalid JSON')
    }
  }

  const loadSample = () => {
    setRaw(JSON.stringify(sampleAuditLog, null, 2))
    setResult(null)
    setError(null)
  }

  return (
    <div className="card">
      <div className="card-header">
        <div>
          <h2>Audit Log Verification</h2>
          <p className="muted">
            Verify signed audit logs generated by the swap SDK.
          </p>
        </div>
        <div className="badge">Client Integrity</div>
      </div>

      <div className="actions">
        <button className="secondary" onClick={loadSample}>
          Load sample
        </button>
      </div>

      <textarea
        className="textarea"
        placeholder="Paste signed audit log JSON"
        rows={12}
        value={raw}
        onChange={(event) => setRaw(event.target.value)}
      />

      <div className="actions">
        <button className="primary" onClick={handleVerify}>
          Verify audit log
        </button>
      </div>

      {error && <div className="alert error">{error}</div>}

      {result && (
        <div className="output">
          <div className="output-header">
            <span>Verification Result</span>
            <span className={result.signatureValid ? 'ok' : 'bad'}>
              {result.signatureValid && result.hashMatches ? 'Valid' : 'Invalid'}
            </span>
          </div>
          <div className="status-grid">
            <div>
              <span className="label">Payload hash</span>
              <span className="mono">{result.payloadHash}</span>
            </div>
            <div>
              <span className="label">Hash matches</span>
              <span>{result.hashMatches ? 'Yes' : 'No'}</span>
            </div>
            <div>
              <span className="label">Signature present</span>
              <span>{result.signaturePresent ? 'Yes' : 'No'}</span>
            </div>
            <div>
              <span className="label">Signature valid</span>
              <span>{result.signatureValid ? 'Yes' : 'No'}</span>
            </div>
            {result.error && (
              <div className="error-text">{result.error}</div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
